<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Illuminate\Support\Arr;

class Task extends Model
{
    //
	use RecordsActivity;

//	protected static function boot()
//	{
//		parent::boot(); // TODO: Change the autogenerated stub
//
//		static::created(function ($task){
//			$task->project->recordActivity('created_task');
//		});
//
////		static::updated(function ($task){
////			if(!$task->completed)
////
////			else
////		});
//	}

	protected $fillable = [
		'body',
		'completed'
	];

	protected $casts = [
		'completed' => 'boolean'
	];

	protected static $recordableEvents = ['created','deleted'];

	public function path(){
		return "/projects/".$this->project->id.'/tasks/'.$this->id;
	}

	public function project(){
		return $this->belongsTo('App\Project');
	}

	public function complete(){
		$this->update(['completed' => true]);
		$this->recordActivity('completed_task');

	}

	public function incomplete(){
		$this->update(['completed' => false]);
		$this->recordActivity('incompleted_task');
	}



}
